= Solution Pattern: Build an extendable Multi-Channel Messaging Platform
:page-layout: home
:sectnums:
:sectlinks:
:doctype: book


As the internet evolves and technologies and trends emerge, so does the way people and organisations connect. Not only is digitalization transforming and automating processes, but also social changes and events are making an impact that is shaping how we interact.

Not so long ago, Email and SMSs started to replace direct phone conversations, and soon after, instant messaging platforms gained popularity over them. Today we have a big landscape of messaging platforms and often we feel divided on which one to use to communicate with family and friends.

On the professional side, organisations mandate one common communication platform for all associates, but often, more than one survives, specially when integrating with external parties, or for example, when companies are acquired and need to be connected.

As an example, let's discuss how support teams may operate in an organisation. Telephone / email are channels that start getting old fashioned. Organisations may enable instant messaging platforms, which are more cost effective, and provide a closer and friendlier experience for customers in need to contact support teams. 

Here we address the scenario mentioned in the example above and propose a solution pattern that implements an architecture fit for a diverse range of relatable scenarios.


*Contributors*: _Bruno Meseguer (Red Hat), Bernard Tison (Red Hat), Jaya Baskaran (Red Hat)_
++++
 <br>
++++
[NOTE]
====
Solutions Patterns help you understand the art of the possible with Red Hat's portfolio, and are not intended to be used as-is for production environments. You are welcome use any part of this solution pattern for your own workloads.
====

{empty} +

include::01-pattern.adoc[]
